### ISSUE TITLE
Add cop: ObjectDescription

### ISSUE THREAD

**Issue by DmitryTsepelev** [DmitryTsepelev/rubocop-graphql#3]
Good:

```ruby
class Types::UserType < Types::BaseObject
  description "Represents application user"
end
```

**Comment by 0legovich** [comment]
@DmitryTsepelev Hi. I have thought about this problem and can't find an optimal solution yet. 
Problem: in order to recognize that the current class is a "Type", you need to convert the name of this class to a constant and call its ancestors. Because the parent class can be the inheritor of Types:: BaseObject. But we don't have access to the constants of the application where rubocop is called.

For example:
```
class Types::MyClassName < GraphQL::Schema::Object
end

class Types::UserType < Types::MyClassName
end
```
Accordingly it is not possible to call `Object.const_get(Types::UserType)`. 
It may not be reliable to rely on the name of the namespace `Type`, or on the presence of "Type" in the name of the class. Any ideas?

**Comment by DmitryTsepelev** [comment]
@0legovich By default `graphql-ruby` generates a folder called `/graphql` with nested `types` and `mutations` folder (`/graphql` is already used [here](https://github.com/DmitryTsepelev/rubocop-graphql/blob/master/config/default.yml#L4) to avoid running these cops outside of the folder). I think we could start with a pretty simple solution: find out what folders are generated and add some obvious patterns that are missing (types, mutations, subscriptions, resolvers etc.) and use them, users can always extend this list
