### ISSUE TITLE
`GraphQL/FieldDefinitions` support for multiple definitions

### ISSUE THREAD

**Issue by ravangen** [DmitryTsepelev/rubocop-graphql#90]
For `graphql-ruby >= 1.13` ([changelog](https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG.md#1130-24-november-2021)), a schema may now contain multiple members with the same name.

```
example_input.rb:13:9: C: [Corrected] GraphQL/FieldDefinitions: Define resolver method after field definition.
        field( ...
        ^^^^^^
example_input.rb:29:9: C: [Corrected] GraphQL/FieldDefinitions: Define resolver method after field definition.
        field( ...
        ^^^^^^
```

Then it actually changes the order in the code, and move the second field definition under the code method, and if I run it again it does the reverse. Rubocop seems to be confused by the fact that the field is declared twice.

**Comment by DmitryTsepelev** [comment]
Good point, we need to fix that 🙂

**Comment by toneymathews** [comment]
👋🏼 Hi, I'm looking to fix this, should have a PR up for it soon.

**Comment by toneymathews** [comment]
I tried fixing this so that if there are multiple field definitions, the resolver method is added after the last field definition.

Since this cop lints field definitions in general, I thought it can also handle ungrouped field definitions. I’ve written up a [PR](https://github.com/toneymathews/rubocop-graphql/pull/1) for that. This would result in multiple offences in the below example

```ruby
Class UserType < BaseType
  field :count, Integer, null: false

  def count
    object.count
  end

  field :count, UnsignedInt, null: false
  field :count, Float, null: false
end
```

In the above scenario, offences and correction can be expected for the field definition and the resolver method so that the corrected GraphQL object looks like
```ruby
class UserType < BaseType
  field :count, Integer, null: false
  field :count, UnsignedInt, null: false
  field :count, Float, null: false

  def count
    object.count
  end
end
```

I was wondering if 
 - the current rule should just handle field definitions so that, the resolver method is added at the end of the last field definition if there are multiple field definitions for a field?
-  grouping multiple field definitions must be a separate cop since this one is pretty big and can to be a separate rule in itself (`GraphQL/MultipleFieldDefinitions`)? 

If you think otherwise, I can refine this PR so that multiple field definitions are supported for `group_definitions` style as well and add tests.

**Comment by toneymathews** [comment]
Hi @DmitryTsepelev , I was hoping to get an update regarding this approach to take in this case. Whether this should be two separate cops or we can club it as one?

**Comment by DmitryTsepelev** [comment]
Hi @toneymathews! Sorry for the radio silence, I think I'd like to have a separate cop for that cause as you said it's rather big already. Will be happy to review the PR!

**Comment by toneymathews** [comment]
I've added https://github.com/DmitryTsepelev/rubocop-graphql/pull/94 as a fix.
