### ISSUE TITLE
GraphQL/ObjectDescription is happening to Unit Test class under test/graphql folder

### ISSUE THREAD

**Issue by eddiecheung-shopify** [DmitryTsepelev/rubocop-graphql#95]
#### Description

I am getting `GraphQL/ObjectDescription: Missing type description` from those Unit Testing class, located under `test/graphql` folder for testing graphql related classes.

#### Workaround

Currently, I am using the following setting in `.rubocop.yml` to bypass the linter check:

```yml
GraphQL/ObjectDescription:
  Exclude:
    - test/graphql/types/*.rb
    - test/graphql/*.rb
 ```

#### Question

I would like to know is there a better way to address this? Is there a way to add object description to unit test class?

**Comment by DmitryTsepelev** [comment]
Hi @eddiecheung-shopify! That's weird, https://github.com/DmitryTsepelev/rubocop-graphql/blob/master/config/default.yml#L7 should do the same thing and exclude all specs/tests. Could you please check that the global rule is not redefined anywhere?

**Comment by eddiecheung-shopify** [comment]
Hi @DmitryTsepelev will it be our `.rubocop.yml` config file override this default setting? 

By the way, I am using version `0.14.6`, and with other rubo gem:
![image](https://user-images.githubusercontent.com/83414872/192787671-8ad9378c-5e15-4141-8ef2-c1bc9005f8b5.png)

**Comment by DmitryTsepelev** [comment]
@eddiecheung-shopify sorry for the radio silence 😞 yes, the local `.rubocop.yml` will be merged with the default one, and the local one will be prioritized

**Comment by eddiecheung-shopify** [comment]
Thanks @DmitryTsepelev for your reply. I think you have answered my question so I will close this ticket.

**Comment by chasingmaxwell** [comment]
I'm running into this right now as well. It looks like with the current default configuration, the [Exclude configuration for GraphQL/ObjectDescription](https://github.com/DmitryTsepelev/rubocop-graphql/blob/master/config/default.yml#L136) is overriding the [Exclude configuration for the GraphQL department](https://github.com/DmitryTsepelev/rubocop-graphql/blob/master/config/default.yml#L5). Because of this, implementations with a `graphql` directory inside their `test` or `spec` directories will have to specify the `Exclude` configuration for the `GraphQL/ObjectDescription` cop with all items from the department and cop `Exclude` configurations:

```yaml
GraphQL/ObjectDescription:
  Exclude:
    - '**/*_schema.rb'
    - '**/base_*.rb'
    - '**/graphql/query_context.rb'
    - 'spec/**/*'
    - 'test/**/*'
```

Probably the default configuration should specify the `spec/**/*` and `test/**/*` excludes in the `GraphQL/ObjectDescription` cop configuration. I'll put together a PR with that change.
